// Include the `blueprotobuf` module, which is generated from blueprotobuf.proto.
pub mod blueprotobuf {
    // Generated by [`prost-build`]
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/blueprotobuf_package.rs"));
    // Generated by [`pbjson-build`]
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/blueprotobuf_package.serde.rs"));
}

use crate::blueprotobuf::EEntityType;

impl From<i64> for EEntityType {
    fn from(entity_type: i64) -> Self {
        match entity_type & 0xffff {
            64 => EEntityType::EntMonster,
            640 => EEntityType::EntChar,
            _ => EEntityType::EntErrType,
        }
    }
}

// impl From<i32> for EDamageType {
//     fn from(entity_type: i32) -> Self {
//         match entity_type {
//             0 => EDamageType::Normal,
//             1 => EDamageType::Miss,
//             2 => EDamageType::Heal,
//             3 => EDamageType::Immune,
//             4 => EDamageType::Fall,
//             5 => EDamageType::Absorbed,
//             _ => EDamageType::Normal,
//         }
//     }
// }
