
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async enableBlur() : Promise<void> {
    await TAURI_INVOKE("enable_blur");
},
async disableBlur() : Promise<void> {
    await TAURI_INVOKE("disable_blur");
},
async copySyncContainerData() : Promise<void> {
    await TAURI_INVOKE("copy_sync_container_data");
},
async getHeaderInfo() : Promise<Result<HeaderInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_header_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDpsPlayerWindow() : Promise<PlayersWindow> {
    return await TAURI_INVOKE("get_dps_player_window");
},
async getDpsSkillWindow(playerUidStr: string) : Promise<Result<SkillsWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dps_skill_window", { playerUidStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDpsBossOnlyPlayerWindow() : Promise<PlayersWindow> {
    return await TAURI_INVOKE("get_dps_boss_only_player_window");
},
async getDpsBossOnlySkillWindow(playerUidStr: string) : Promise<Result<SkillsWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dps_boss_only_skill_window", { playerUidStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHealPlayerWindow() : Promise<PlayersWindow> {
    return await TAURI_INVOKE("get_heal_player_window");
},
async getHealSkillWindow(playerUidStr: string) : Promise<Result<SkillsWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_heal_skill_window", { playerUidStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetEncounter() : Promise<void> {
    await TAURI_INVOKE("reset_encounter");
},
async togglePauseEncounter() : Promise<void> {
    await TAURI_INVOKE("toggle_pause_encounter");
},
async hardReset() : Promise<void> {
    await TAURI_INVOKE("hard_reset");
},
async getTestPlayerWindow() : Promise<PlayersWindow> {
    return await TAURI_INVOKE("get_test_player_window");
},
async getTestSkillWindow(playerUid: string) : Promise<Result<SkillsWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_test_skill_window", { playerUid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type HeaderInfo = { totalDps: number; totalDmg: number; elapsedMs: number; timeLastCombatPacketMs: number }
export type PlayerRow = { uid: number; abilityScore: number; className: string; classSpecName: string; name: string; totalValue: number; valuePerSec: number; valuePct: number; critRate: number; critValueRate: number; luckyRate: number; luckyValueRate: number; hits: number; hitsPerMinute: number }
export type PlayersWindow = { playerRows: PlayerRow[]; localPlayerUid: number; topValue: number }
export type SkillRow = { uid: number; name: string; totalValue: number; valuePerSec: number; valuePct: number; critRate: number; critValueRate: number; luckyRate: number; luckyValueRate: number; hits: number; hitsPerMinute: number }
export type SkillsWindow = { inspectedPlayer: PlayerRow; skillRows: SkillRow[]; localPlayerUid: number; topValue: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
