// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/short.proto

package bpsr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncNearDeltaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaInfos    []*AoiSyncDelta        `protobuf:"bytes,1,rep,name=delta_infos,json=deltaInfos,proto3" json:"delta_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncNearDeltaInfo) Reset() {
	*x = SyncNearDeltaInfo{}
	mi := &file_proto_short_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncNearDeltaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNearDeltaInfo) ProtoMessage() {}

func (x *SyncNearDeltaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_short_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNearDeltaInfo.ProtoReflect.Descriptor instead.
func (*SyncNearDeltaInfo) Descriptor() ([]byte, []int) {
	return file_proto_short_proto_rawDescGZIP(), []int{0}
}

func (x *SyncNearDeltaInfo) GetDeltaInfos() []*AoiSyncDelta {
	if x != nil {
		return x.DeltaInfos
	}
	return nil
}

// Root message that wraps another delta
type SyncToMeDeltaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaInfo     *AoiSyncToMeDelta      `protobuf:"bytes,1,opt,name=delta_info,json=deltaInfo,proto3,oneof" json:"delta_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncToMeDeltaInfo) Reset() {
	*x = SyncToMeDeltaInfo{}
	mi := &file_proto_short_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncToMeDeltaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncToMeDeltaInfo) ProtoMessage() {}

func (x *SyncToMeDeltaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_short_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncToMeDeltaInfo.ProtoReflect.Descriptor instead.
func (*SyncToMeDeltaInfo) Descriptor() ([]byte, []int) {
	return file_proto_short_proto_rawDescGZIP(), []int{1}
}

func (x *SyncToMeDeltaInfo) GetDeltaInfo() *AoiSyncToMeDelta {
	if x != nil {
		return x.DeltaInfo
	}
	return nil
}

type AoiSyncToMeDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field 1: optional AoiSyncDelta
	BaseDelta     *AoiSyncDelta `protobuf:"bytes,1,opt,name=base_delta,json=baseDelta,proto3,oneof" json:"base_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AoiSyncToMeDelta) Reset() {
	*x = AoiSyncToMeDelta{}
	mi := &file_proto_short_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AoiSyncToMeDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AoiSyncToMeDelta) ProtoMessage() {}

func (x *AoiSyncToMeDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_short_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AoiSyncToMeDelta.ProtoReflect.Descriptor instead.
func (*AoiSyncToMeDelta) Descriptor() ([]byte, []int) {
	return file_proto_short_proto_rawDescGZIP(), []int{2}
}

func (x *AoiSyncToMeDelta) GetBaseDelta() *AoiSyncDelta {
	if x != nil {
		return x.BaseDelta
	}
	return nil
}

// AoiSyncDelta message
type AoiSyncDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillEffects  *SkillEffect           `protobuf:"bytes,7,opt,name=skill_effects,json=skillEffects,proto3,oneof" json:"skill_effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AoiSyncDelta) Reset() {
	*x = AoiSyncDelta{}
	mi := &file_proto_short_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AoiSyncDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AoiSyncDelta) ProtoMessage() {}

func (x *AoiSyncDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_short_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AoiSyncDelta.ProtoReflect.Descriptor instead.
func (*AoiSyncDelta) Descriptor() ([]byte, []int) {
	return file_proto_short_proto_rawDescGZIP(), []int{3}
}

func (x *AoiSyncDelta) GetSkillEffects() *SkillEffect {
	if x != nil {
		return x.SkillEffects
	}
	return nil
}

// SkillEffect message
type SkillEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Damages       []*SyncDamageInfo      `protobuf:"bytes,2,rep,name=damages,proto3" json:"damages,omitempty"`
	TotalDamage   *int64                 `protobuf:"varint,3,opt,name=total_damage,json=totalDamage,proto3,oneof" json:"total_damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillEffect) Reset() {
	*x = SkillEffect{}
	mi := &file_proto_short_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillEffect) ProtoMessage() {}

func (x *SkillEffect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_short_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillEffect.ProtoReflect.Descriptor instead.
func (*SkillEffect) Descriptor() ([]byte, []int) {
	return file_proto_short_proto_rawDescGZIP(), []int{4}
}

func (x *SkillEffect) GetDamages() []*SyncDamageInfo {
	if x != nil {
		return x.Damages
	}
	return nil
}

func (x *SkillEffect) GetTotalDamage() int64 {
	if x != nil && x.TotalDamage != nil {
		return *x.TotalDamage
	}
	return 0
}

// SyncDamageInfo message
type SyncDamageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActualValue   *int64                 `protobuf:"varint,7,opt,name=actual_value,json=actualValue,proto3,oneof" json:"actual_value,omitempty"`
	Value         *int64                 `protobuf:"varint,6,opt,name=value,proto3,oneof" json:"value,omitempty"`
	LuckyValue    *int64                 `protobuf:"varint,8,opt,name=lucky_value,json=luckyValue,proto3,oneof" json:"lucky_value,omitempty"`
	TopSummonerId *int64                 `protobuf:"varint,21,opt,name=top_summoner_id,json=topSummonerId,proto3,oneof" json:"top_summoner_id,omitempty"`
	AttackerUuid  *int64                 `protobuf:"varint,11,opt,name=attacker_uuid,json=attackerUuid,proto3,oneof" json:"attacker_uuid,omitempty"`
	OwnerId       *int32                 `protobuf:"varint,12,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDamageInfo) Reset() {
	*x = SyncDamageInfo{}
	mi := &file_proto_short_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDamageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDamageInfo) ProtoMessage() {}

func (x *SyncDamageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_short_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDamageInfo.ProtoReflect.Descriptor instead.
func (*SyncDamageInfo) Descriptor() ([]byte, []int) {
	return file_proto_short_proto_rawDescGZIP(), []int{5}
}

func (x *SyncDamageInfo) GetActualValue() int64 {
	if x != nil && x.ActualValue != nil {
		return *x.ActualValue
	}
	return 0
}

func (x *SyncDamageInfo) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *SyncDamageInfo) GetLuckyValue() int64 {
	if x != nil && x.LuckyValue != nil {
		return *x.LuckyValue
	}
	return 0
}

func (x *SyncDamageInfo) GetTopSummonerId() int64 {
	if x != nil && x.TopSummonerId != nil {
		return *x.TopSummonerId
	}
	return 0
}

func (x *SyncDamageInfo) GetAttackerUuid() int64 {
	if x != nil && x.AttackerUuid != nil {
		return *x.AttackerUuid
	}
	return 0
}

func (x *SyncDamageInfo) GetOwnerId() int32 {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return 0
}

var File_proto_short_proto protoreflect.FileDescriptor

const file_proto_short_proto_rawDesc = "" +
	"\n" +
	"\x11proto/short.proto\x12\x05short\"I\n" +
	"\x11SyncNearDeltaInfo\x124\n" +
	"\vdelta_infos\x18\x01 \x03(\v2\x13.short.AoiSyncDeltaR\n" +
	"deltaInfos\"_\n" +
	"\x11SyncToMeDeltaInfo\x12;\n" +
	"\n" +
	"delta_info\x18\x01 \x01(\v2\x17.short.AoiSyncToMeDeltaH\x00R\tdeltaInfo\x88\x01\x01B\r\n" +
	"\v_delta_info\"Z\n" +
	"\x10AoiSyncToMeDelta\x127\n" +
	"\n" +
	"base_delta\x18\x01 \x01(\v2\x13.short.AoiSyncDeltaH\x00R\tbaseDelta\x88\x01\x01B\r\n" +
	"\v_base_delta\"^\n" +
	"\fAoiSyncDelta\x12<\n" +
	"\rskill_effects\x18\a \x01(\v2\x12.short.SkillEffectH\x00R\fskillEffects\x88\x01\x01B\x10\n" +
	"\x0e_skill_effects\"w\n" +
	"\vSkillEffect\x12/\n" +
	"\adamages\x18\x02 \x03(\v2\x15.short.SyncDamageInfoR\adamages\x12&\n" +
	"\ftotal_damage\x18\x03 \x01(\x03H\x00R\vtotalDamage\x88\x01\x01B\x0f\n" +
	"\r_total_damage\"\xce\x02\n" +
	"\x0eSyncDamageInfo\x12&\n" +
	"\factual_value\x18\a \x01(\x03H\x00R\vactualValue\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x06 \x01(\x03H\x01R\x05value\x88\x01\x01\x12$\n" +
	"\vlucky_value\x18\b \x01(\x03H\x02R\n" +
	"luckyValue\x88\x01\x01\x12+\n" +
	"\x0ftop_summoner_id\x18\x15 \x01(\x03H\x03R\rtopSummonerId\x88\x01\x01\x12(\n" +
	"\rattacker_uuid\x18\v \x01(\x03H\x04R\fattackerUuid\x88\x01\x01\x12\x1e\n" +
	"\bowner_id\x18\f \x01(\x05H\x05R\aownerId\x88\x01\x01B\x0f\n" +
	"\r_actual_valueB\b\n" +
	"\x06_valueB\x0e\n" +
	"\f_lucky_valueB\x12\n" +
	"\x10_top_summoner_idB\x10\n" +
	"\x0e_attacker_uuidB\v\n" +
	"\t_owner_idB\x0eZ\fbpsr/v1;bpsrb\x06proto3"

var (
	file_proto_short_proto_rawDescOnce sync.Once
	file_proto_short_proto_rawDescData []byte
)

func file_proto_short_proto_rawDescGZIP() []byte {
	file_proto_short_proto_rawDescOnce.Do(func() {
		file_proto_short_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_short_proto_rawDesc), len(file_proto_short_proto_rawDesc)))
	})
	return file_proto_short_proto_rawDescData
}

var file_proto_short_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_short_proto_goTypes = []any{
	(*SyncNearDeltaInfo)(nil), // 0: short.SyncNearDeltaInfo
	(*SyncToMeDeltaInfo)(nil), // 1: short.SyncToMeDeltaInfo
	(*AoiSyncToMeDelta)(nil),  // 2: short.AoiSyncToMeDelta
	(*AoiSyncDelta)(nil),      // 3: short.AoiSyncDelta
	(*SkillEffect)(nil),       // 4: short.SkillEffect
	(*SyncDamageInfo)(nil),    // 5: short.SyncDamageInfo
}
var file_proto_short_proto_depIdxs = []int32{
	3, // 0: short.SyncNearDeltaInfo.delta_infos:type_name -> short.AoiSyncDelta
	2, // 1: short.SyncToMeDeltaInfo.delta_info:type_name -> short.AoiSyncToMeDelta
	3, // 2: short.AoiSyncToMeDelta.base_delta:type_name -> short.AoiSyncDelta
	4, // 3: short.AoiSyncDelta.skill_effects:type_name -> short.SkillEffect
	5, // 4: short.SkillEffect.damages:type_name -> short.SyncDamageInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_short_proto_init() }
func file_proto_short_proto_init() {
	if File_proto_short_proto != nil {
		return
	}
	file_proto_short_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_short_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_short_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_short_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_short_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_short_proto_rawDesc), len(file_proto_short_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_short_proto_goTypes,
		DependencyIndexes: file_proto_short_proto_depIdxs,
		MessageInfos:      file_proto_short_proto_msgTypes,
	}.Build()
	File_proto_short_proto = out.File
	file_proto_short_proto_goTypes = nil
	file_proto_short_proto_depIdxs = nil
}
